=== ManuelVillarVitoria/xslt/marcadores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="marcadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pagina" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <!-- Element initials no obligatori -->
              <xs:element name="initials" minOccurs="0" maxOccurs="unbounded">
                <xs:simpleType>
                  <!-- Restriccio de tipus string obligatori tres lletres -->
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z][a-zA-Z][a-zA-Z]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="descripcion" type="xs:string"/>
              <xs:element name="url" type="xs:string"/>
              <xs:element name="option">
                <xs:complexType>
                <!-- Atribut de l'element option obligatori -->
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="value" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ManuelVillarVitoria/xslt/marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="marcadores.xsd">
   <pagina>
      <nombre>Abrirllave</nombre>
      <initials>HFS</initials>
      <descripcion>Tutoriales de informática.</descripcion>
      <url>http://www.abrirllave.com/</url>
      <option value="hola">dsfsd</option>
   </pagina>
   <pagina>
      <nombre>Wikipedia</nombre>
      <initials>HFS</initials>
      <descripcion>La enciclopedia libre.</descripcion>
      <url>http://www.wikipedia.org/</url>
      <option value="sdas">sdfsd</option>
   </pagina>
   <pagina>
      <nombre>W3C</nombre>
      <descripcion>World Wide Web Consortium.</descripcion>
      <url>http://www.w3.org/</url>
      <option value="hola"></option>
   </pagina>
</marcadores>
