=== ManuelVillarVitoria/xslt/nota.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="note">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="to" type="xs:string"/>
      <xs:element name="from" type="xs:string"/>
      <xs:element name="datenote" type="xs:date"/>
      <xs:element name="timenote" type="xs:time" minOccurs="0" maxOccurs="1"/>
      <xs:element name="phone">
        <xs:complexType>
        <!-- Atribut de l'element phone obligatori -->
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="callback" type="xs:boolean" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
    </xs:element>      
      <xs:element name="heading" type="xs:string"/>
      <xs:element name="body" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== ManuelVillarVitoria/xslt/nota.xml
<?xml version="1.0"?>
<note xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com nota.xsd">
  <to>Tove</to>
  <from>Jani</from>
  <datenote>2016-02-29</datenote>
  <timenote>13:20:00</timenote>
  <phone callback="1">8-678-9887</phone>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
